# Generated by Django 5.2.11 on 2026-02-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="stream_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MJPEG stream URL, e.g. http://192.168.1.50:81/stream",
                max_length=300,
            ),
        ),
    ]
