# Generated by Django 5.2.11 on 2026-04-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_stream_url_to_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('detection', 'Face Detection'), ('alert_created', 'Alert Created'), ('alert_ack', 'Alert Acknowledged'), ('mode_change', 'Security Mode Changed'), ('person_added', 'Known Person Added'), ('person_removed', 'Known Person Removed'), ('device_added', 'Device Added'), ('device_updated', 'Device Updated'), ('door_opened', 'Door Opened'), ('door_closed', 'Door Closed'), ('settings_changed', 'Settings Changed')], max_length=30),
        ),
        migrations.CreateModel(
            name='DoorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_events', to='core.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='core_doorev_device__08c490_idx'), models.Index(fields=['status', '-created_at'], name='core_doorev_status_11a9aa_idx')],
            },
        ),
    ]
