# Generated by Django 5.2.11 on 2026-04-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activitylog_action_doorevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knownperson',
            name='embedding',
            field=models.TextField(blank=True, help_text='JSON-serialized 512-dim ArcFace embedding vector (legacy/primary)', null=True),
        ),
        migrations.CreateModel(
            name='KnownPersonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='known_persons/extra/')),
                ('embedding', models.TextField(help_text='JSON-serialized 512-dim ArcFace embedding vector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.knownperson')),
            ],
        ),
    ]
