# Generated by Django 5.2.11 on 2026-02-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_otp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="6-digit OTP for password reset",
                max_length=6,
            ),
        ),
    ]
